title: Pizza Project
email: seth@sethw.me
description: >-
  A simple and efficient website for ordering high quality pizzas.
url: "https://pizza-project.sethw.me/"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - api
